task :default => :s

task :s => "server"
desc "[s] server"
task :server do
  system %(vue-cli-service serve --port 3995 --open)
end

task :b => "build"
desc "[b] build"
task :build do
  require "pathname"
  require "json"
  package = JSON.parse(Pathname("../package.json").read)
  version = package["version"]
  p version

  system %(NODE_ENV=development vue-cli-service build --dest top/dist --inline-vue --target wc --name shogi-player-wc src/components/ShogiPlayerWcRoot.vue)
  system %(open top/test.html)
end
