source "https://rubygems.org"

gem "json"
gem "table_format"
gem "capybara", require: "capybara/dsl"
gem "webdrivers"
# gem "selenium-webdriver"
gem "rspec"
# gem "test-unit"
gem "table_format"
gem "power_assert"
gem "rake"
gem "minitest"
gem "minitest-power_assert"
