task :default => :s

task :s => :server
desc "[s] server"
task :server do
  system <<~EOT
  vuepress dev docs -p 5001 --open --no-cache
  EOT
end

task :b => :build
desc "[b] build"
task :build do
  system <<~EOT
  vuepress build docs
  EOT
end
