task :default => :s

task :s => "server"
desc "[s] server"
task :server do
  system <<~EOT
  vue-cli-service serve --port 3995 --open
  EOT
end

task :b => "build"
desc "[b] build"
task :build do
  system <<~EOT
  SP_TARGET=wc vue-cli-service build --mode development --dest labo/shogi-player-wc/dist --inline-vue --target wc --name shogi-player-wc src/components/ShogiPlayerLib.vue
  open labo/shogi-player-wc/index.html
  EOT
end

task :m => "my_tag"
desc "[m] my_tag"
task :my_tag do
  system <<~EOT
  SP_TARGET=wc vue-cli-service build --mode development --dest labo/my-tag/dist --inline-vue --target wc --name my-tag src/components/MyTag.vue
  open labo/my-tag/index.html
  EOT
end

task :l => "my_lib"
desc "[l] my_lib"
task :my_lib do
  system <<~EOT
  SP_TARGET=wc vue-cli-service build --mode development --dest labo/my_lib/dist --target lib --name my_tag src/components/MyLib.vue
  open labo/my_lib/index.html
  EOT
end
