task :default => :s

task :s => :server
desc "[s] server"
task :server do
  system %(vuepress dev -p 5001 --open)
end

task :b => :build
desc "[b] build"
task :build do
  system %(vuepress build)
end
