#!/usr/bin/env ruby
require "pathname"

Pathname(".").glob("**/*.{vue,scss,sass}") do |file|
  puts file.readlines.grep(/^\s*\-\-/).collect { |e| [e.strip, "(in #{file})"].join(" ") }
end
# >> --sp_board_piece_rate: 90%                           // 盤のセル内の駒占有率 (in PieceObject.vue)
# >> --sp_stand_piece_w: 47px                             // 駒台のセル(W) (in PieceObject.vue)
# >> --sp_stand_piece_h: 50px                             // 駒台のセル(H) (in PieceObject.vue)
# >> --sp_stand_piece_rate: 80%                           // 駒台のセル内の駒占有率 (in PieceObject.vue)
# >> --sp_piece_box_piece_w: 38px                         // 駒箱のセル(W) (in PieceObject.vue)
# >> --sp_piece_box_piece_h: 46px                         // 駒箱のセル(H) (in PieceObject.vue)
# >> --sp_piece_box_piece_rate: 90%                       // 駒箱のセル内の駒占有率 (in PieceObject.vue)
# >> --sp_stand_piece_w_mobile: 38px                      // 駒台のセル(W) ※モバイル時 (in PieceObject.vue)
# >> --sp_stand_piece_h_mobile: 46px                      // 駒台のセル(H) ※モバイル時 (in PieceObject.vue)
# >> --sp_stand_piece_rate_mobile: 90%                    // 駒台のセル内の駒占有率 ※モバイル時 (in PieceObject.vue)
# >> --sp_piece_box_piece_w_mobile: 38px                  // 駒箱のセル(W) ※モバイル時 (in PieceObject.vue)
# >> --sp_piece_box_piece_h_mobile: 46px                  // 駒箱のセル(H) ※モバイル時 (in PieceObject.vue)
# >> --sp_piece_box_piece_rate_mobile: 90%                // 駒箱のセル内の駒占有率 ※モバイル時 (in PieceObject.vue)
# >> --sp_grid_color: rgba(0, 0, 0, 0.5)                  // グリッド色 (in BoardOuter.vue)
# >> --sp_board_padding: 2%                               // 盤の隅の隙間 (in BoardOuter.vue)
# >> --sp_grid_outer_stroke: 1px                          // 升目外枠の太さ (in BoardOuter.vue)
# >> --sp_grid_star: 6px                                  // 星の大きさ (in BoardOuter.vue)
# >> --sp_board_radius: 0.5%                              // 盤の隅の丸め度合い (in BoardOuter.vue)
# >> --sp_board_color: rgba(0, 0, 0, 0.2)                 // 盤の色 (in BoardOuter.vue)
# >> --sp_board_opacity: 1.0                              // 非半透明度 (in BoardOuter.vue)
# >> --sp_board_bg_image: none                            // 背景画像 (in BoardOuter.vue)
# >> --sp_body_width: 100%                                // 盤(駒台を含む)の幅 (in ShogiPlayerWidth.vue)
# >> --sp_piece_count_gap_right: 86%                      // 駒数の駒右端からのオフセット(横配置時) (in PieceObjectCount.vue)
# >> --sp_piece_count_gap_bottom: 100%                    // 駒数の駒底辺からのオフセット(縦配置時) (in PieceObjectCount.vue)
# >> --sp_piece_count_font_size: 0.75rem                  // 駒数の文字サイズ (in PieceObjectCount.vue)
# >> --sp_piece_count_font_color:  rgba(0, 0, 0, 0.75)    // 駒数の文字色 (in PieceObjectCount.vue)
# >> --sp_piece_count_bg_color: rgba(255, 255, 255, 0.75) // 駒数の文字色背景 (in PieceObjectCount.vue)
# >> --sp_piece_count_padding: 3px                        // 駒数のパディング (in PieceObjectCount.vue)
# >> --sp_edit_tool_box_margin_bottom: 0.5rem             // edit_mode時の上のボタンの下のマージン (in EditToolBox.vue)
# >> --sp_ground_color: inherit                           // グラウンド背景色 (in ShogiPlayerGround.vue)
# >> --sp_ground_bg_image: none                           // グラウンド背景画像 (in ShogiPlayerGround.vue)
# >> --sp_piece_box_color: rgba(0, 0, 0, 0.2)             // 駒箱背景 (in PieceBox.vue)
# >> --sp_piece_box_radius: 3px                           // 角丸度合 (in PieceBox.vue)
# >> --sp_piece_box_margin_top: 10px                      // 横レイアウト時の上マージン (in PieceBox.vue)
# >> --sp_board_aspect_ratio: 109.7%                      // 盤の横を100としたときの縦の比率 (in AspectRatioFixedBlock.vue)
# >> --sp_shadow_offset: 2;                               // 右下方法への長さ (in stylesheets/new_initial_variables.scss)
# >> --sp_shadow_blur: 3;                                 // 影の範囲 (in stylesheets/new_initial_variables.scss)
# >> --sp_shadow_color: rgba(0, 0, 0, 0.4);               // 色 (in stylesheets/new_initial_variables.scss)
