#!/bin/sh
cp original/0OU.png BK0.png
cp original/0HI.png BR0.png
cp original/0KA.png BB0.png
cp original/0KI.png BG0.png
cp original/0GI.png BS0.png
cp original/0KE.png BN0.png
cp original/0KY.png BL0.png
cp original/0FU.png BP0.png
cp original/0GY.png BX0.png
cp original/0RY.png BR1.png
cp original/0UM.png BB1.png
cp original/0NG.png BS1.png
cp original/0NK.png BN1.png
cp original/0NY.png BL1.png
cp original/0TO.png BP1.png

cp original/1OU.png WK0.png
cp original/1HI.png WR0.png
cp original/1KA.png WB0.png
cp original/1KI.png WG0.png
cp original/1GI.png WS0.png
cp original/1KE.png WN0.png
cp original/1KY.png WL0.png
cp original/1FU.png WP0.png
cp original/1GY.png WX0.png
cp original/1RY.png WR1.png
cp original/1UM.png WB1.png
cp original/1NG.png WS1.png
cp original/1NK.png WN1.png
cp original/1NY.png WL1.png
cp original/1TO.png WP1.png
